#server:
#  port: 80
#
#
#spring:
#  application:
#    name: cloud-consumer-order
#
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://localhost:3306/transportdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: zedongMySQL
#    password: 123456
#eureka:
#  client:
#    #表示是否将自己注册进EurekaServer默认为true
#    register-with-eureka: true
#    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true，才是配合ribbon使用负载均衡
#    fetch-registry: true
#    service-url:
#      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
##      defaultZone: http://127.0.0.1:7001/eureka/
#       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #集群版
#  instance:
#    instance-id: cousumerOrder80
#    prefer-ip-address: true  #访问路径显示IP
#
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.checc.data.entities
#
##设置feign客户端超时时间（OpenFeign默认支持ribbon）
#ribbon:
#  #建立连接所用时间
#  ReadTimeout: 5000
#  #建立连接后从服务器读取到可用资源所用时间
#  ConnectTimeout: 5000
#logging:
#  pattern:
#    pattern:
#      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
#  level:
#    com.checc.data: debug
##开启feign hystrix支持
#feign:
#  hystrix:
#    enabled: true
