server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  cloud:
    stream:
      bindings:
        output:
          binder: defaultRabbit
          destination: subscribe
          content-type: application/json
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${spring.rabbitmq.host}
                port: ${spring.rabbitmq.port}
                username: ${spring.rabbitmq.username}
                password: ${spring.rabbitmq.password}
                virtual-host: /

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/transportdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: zedongMySQL
    password: 123456

  rabbitmq:
    host: 10.25.111.113
    port: 5672
    username: admin
    password: admin123

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
      #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true，才是配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true  #访问路径显示IP


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.checc.gateway.entities