server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  security:
    user:
      name: checc
      password: checc
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:  #全局跨域配置
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能 利用微服务名进行路由
      routes:
        - id: order_routh                  #路由id，唯一，建议配合服务名
          uri: lb://tocc-consumer-order   #匹配后提供服务的路由地址
          predicates:
            - Path=/consumer/getFeign/**  #断言，路径相匹配的进行路由
        - id: tocc_auth                  #路由id，唯一，建议配合服务名
          uri: lb://tocc-auth   #匹配后提供服务的路由地址
          predicates:
            - Path=/login,/getInfo   # 断言，路径相匹配的进行路由
        - id: tocc_auth                  #路由id，唯一，建议配合服务名
          uri: lb://tocc-system   #匹配后提供服务的路由地址
          predicates:
            - Path=/**/**/**  #断言，路径相匹配的进行路由
        - id: payment_routh
          uri: lb://tocc-payment-service
          predicates:
            - Path=/payment/get/**
#            - Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性而且值为整数的正则表达式

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
      #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true，才是配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: gateway9527
    prefer-ip-address: true  #访问路径显示IP

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms

# token配置
token:
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

