server:
  port: 8002
# token配置
token:
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

spring:
  application:
    name: tocc-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/transportdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: zedongMySQL
    password: 123456

  elasticsearch:
    rest:
      uris: ["10.25.111.113:9200"]
  data:
    elasticsearch:
      client:
        reactive:
          connection-timeout: 3000
      repositories:
        enabled: true
      cluster-name: docker-cluster
      cluster-nodes: 10.25.111.113:9300

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
      #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true，才是配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8002
    prefer-ip-address: true  #访问路径显示IP

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.checc.gateway.entities

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 10.25.111.113:22122